# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference - status
version: 2.1


#orbs:
#  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.6
    steps:
      - checkout
      - run: echo "snapshot"
      - run: echo -e $GPG_KEY | base64 --decode | gpg --batch --no-tty --import --yes
      - run: ./mvnw clean install
      - run: echo "$SETTINGS" | base64 --decode > settings.xml
      - run: cat settings.xml
      - run: ./mvnw clean deploy -P release -s settings.xml

workflows:
  build_and_deploy:
    jobs:
      - build
